const MINUTE_MS = 60 * 1000;
const HOUR_MS = 60 * MINUTE_MS;
const DAY_MS = 24 * HOUR_MS;

export type SessionStrategy = {
	ACCESS_TOKEN_LIFETIME: number;
	REFRESH_TOKEN_LIFETIME: number;
	MAX_SESSION_LIFETIME: number;
	POP_TOKEN_LIFETIME: number;
	IDLE_TIMEOUT: number;
	SLIDING_SESSION: boolean;
	TOKEN_ROTATION: boolean;
	USE_OFFLINE_ACCESS: boolean;
};

const SHORT_VALS = [5, 8];
// const SHORT_VALS = [1, 2];

export const SESSION_PRESETS = {
	A: {
		ACCESS_TOKEN_LIFETIME: 5 * MINUTE_MS,
		REFRESH_TOKEN_LIFETIME: 90 * DAY_MS,
		MAX_SESSION_LIFETIME: 90 * DAY_MS,
		POP_TOKEN_LIFETIME: 90 * DAY_MS,
		IDLE_TIMEOUT: 90 * DAY_MS,
		SLIDING_SESSION: true,
		TOKEN_ROTATION: true,
		USE_OFFLINE_ACCESS: true,
	},
	B: {
		ACCESS_TOKEN_LIFETIME: 5 * MINUTE_MS,
		REFRESH_TOKEN_LIFETIME: 180 * DAY_MS,
		MAX_SESSION_LIFETIME: 180 * DAY_MS,
		POP_TOKEN_LIFETIME: 180 * DAY_MS,
		IDLE_TIMEOUT: 180 * DAY_MS,
		SLIDING_SESSION: true,
		TOKEN_ROTATION: true,
		USE_OFFLINE_ACCESS: true,
	},
	C: {
		ACCESS_TOKEN_LIFETIME: 5 * MINUTE_MS,
		REFRESH_TOKEN_LIFETIME: 30 * DAY_MS,
		MAX_SESSION_LIFETIME: 30 * DAY_MS,
		POP_TOKEN_LIFETIME: 30 * DAY_MS,
		IDLE_TIMEOUT: 30 * DAY_MS,
		SLIDING_SESSION: true,
		TOKEN_ROTATION: true,
		USE_OFFLINE_ACCESS: true,
	},
	SHORT_NO_OFFLINE: {
		ACCESS_TOKEN_LIFETIME: SHORT_VALS[0] * MINUTE_MS,
		REFRESH_TOKEN_LIFETIME: SHORT_VALS[1] * HOUR_MS,
		MAX_SESSION_LIFETIME: SHORT_VALS[1] * HOUR_MS,
		POP_TOKEN_LIFETIME: SHORT_VALS[1] * HOUR_MS,
		IDLE_TIMEOUT: SHORT_VALS[1] * HOUR_MS,
		SLIDING_SESSION: true,
		TOKEN_ROTATION: true,
		USE_OFFLINE_ACCESS: false,
	},
} satisfies Record<string, SessionStrategy>;

export type SessionPresetName = keyof typeof SESSION_PRESETS;

export const DEFAULT_SESSION_PRESET: SessionPresetName = "A";

const requestedPreset = (process.env.SESSION_PRESET || DEFAULT_SESSION_PRESET) as SessionPresetName;

export const SESSION_PRESET: SessionPresetName =
	requestedPreset in SESSION_PRESETS ? requestedPreset : DEFAULT_SESSION_PRESET;

export const SESSION_STRATEGY: SessionStrategy = SESSION_PRESETS[SESSION_PRESET];
