capabilities:
  tools.inspect:
    roles: [admin, manager]
  tab.graphql:
    roles: [admin]
  tab.files:
    roles: [admin]
  tab.s3commander:
    roles: [admin]
  tab.tools:
    roles: [admin]
  tab.log:
    roles: [admin]
  tab.develop:
    roles: [admin1]
